// js/data_notion_overrides.js
// Generated by tools/sync_notion.py --pull-overrides
// Only contains whitelisted fields. Core reward logic stays in js/data_*.js.

const NOTION_OVERRIDES = {
    version: 1,
    cards: {},
    modules: {},
    campaigns: {},
    campaignSections: {},
    conversions: {}
};
