// js/data_notion_core_overrides.js
// Generated by tools/sync_notion.py --pull-core
// Core overrides are higher risk: validate with golden cases before merge.
const NOTION_CORE_OVERRIDES = {
  "version": 1,
  "cards": {},
  "modules": {
    "easy_moneyback_bonus": {
      "desc": "Easy Card 易賞錢6倍 (2.4%)",
      "rate": 0.024,
      "promo_end": "2026-12-31",
      "valid_from": "2025-05-19",
      "valid_to": "2026-12-31"
    },
    "pulse_china_bonus": {
      "desc": "中國內地/澳門流動支付 (2%)",
      "rate": 0.02,
      "promo_end": "2026-06-30",
      "valid_from": "2026-01-01",
      "valid_to": "2026-06-30",
      "cap_mode": "spending",
      "cap_limit": 80000,
      "cap_key": "pulse_china_bonus_cap"
    },
    "red_designated_bonus": {
      "desc": "Red 指定商戶 (7.6%)",
      "rate": 0.076,
      "promo_end": "2026-03-31",
      "valid_from": "2025-09-01",
      "valid_to": "2026-03-31",
      "cap_mode": "reward",
      "cap_limit": 100,
      "cap_key": "red_designated_cap"
    },
    "red_hot_variable": {
      "desc": "最紅自主獎賞",
      "rate_per_x": 0.004,
      "promo_end": "2026-12-31",
      "valid_from": "2026-01-01",
      "valid_to": "2026-12-31",
      "cap_mode": "reward",
      "cap_limit": 2000,
      "cap_key": "red_hot_variable_cap"
    },
    "red_online": {
      "desc": "Red 網上購物 (3.6%)",
      "rate": 0.04,
      "promo_end": "2026-03-31",
      "valid_from": "2025-09-01",
      "valid_to": "2026-03-31",
      "cap_mode": "reward",
      "cap_limit": 400,
      "cap_key": "red_online_cap"
    },
    "student_tuition_bonus": {
      "desc": "學費回贈 (2.4%)",
      "rate": 0.024,
      "promo_end": "2026-03-31",
      "valid_from": "2025-10-01",
      "valid_to": "2026-03-31",
      "cap_mode": "reward",
      "cap_limit": 200,
      "cap_key": "student_tuition_cap"
    },
    "vs_red_hot_bonus": {
      "desc": "Visa Signature 特別獎賞 (1.2%)",
      "rate_per_x": 0.004,
      "multiplier": 3,
      "promo_end": "2026-12-31",
      "valid_from": "2026-01-01",
      "valid_to": "2026-12-31",
      "cap_mode": "spending",
      "cap_limit": 100000,
      "cap_key": "vs_red_hot_bonus_cap"
    }
  },
  "campaigns": {
    "em_promo": {
      "name": "EveryMile 外幣簽帳優惠",
      "period_policy": {
        "windows": [
          {
            "startDate": "2026-04-01",
            "endDate": "2026-06-30",
            "period": {
              "type": "promo",
              "startDay": 1,
              "startDate": "2026-04-01",
              "endDate": "2026-06-30"
            },
            "id": "window_2"
          },
          {
            "id": "window_1",
            "startDate": "2026-01-01",
            "endDate": "2026-03-31",
            "period": {
              "type": "promo",
              "startDate": "2026-01-01",
              "endDate": "2026-03-31"
            },
            "priority": 1
          }
        ],
        "mode": "composite"
      }
    },
    "winter_promo": {
      "name": "HSBC 最紅冬日賞",
      "period_policy": {
        "windows": [
          {
            "id": "window_1",
            "startDate": "2025-12-01",
            "endDate": "2026-02-28",
            "period": {
              "type": "promo",
              "startDate": "2025-12-01",
              "endDate": "2026-02-28"
            },
            "priority": 1
          }
        ],
        "mode": "fixed"
      }
    }
  }
};
