// js/data_notion_core_overrides.js
// Generated by tools/workbench.js apply
// Core overrides are higher risk: validate with golden cases before merge.
const NOTION_CORE_OVERRIDES = {
  "campaigns": {},
  "cards": {
    "hsbc_gold_student": {
      "name": "HSBC 滙財金卡 (學生卡)"
    }
  },
  "categories": {},
  "modules": {
    "red_hot_variable": {
      "desc": "HSBC 最紅自主獎賞"
    }
  },
  "trackers": {
    "winter_tracker": {
      "desc": "❄️ HSBC 最紅冬日賞"
    }
  },
  "version": 1
};
