// js/data_notion_core_overrides.js
// Generated by tools/workbench.js apply
// Core overrides are higher risk: validate with golden cases before merge.
const NOTION_CORE_OVERRIDES = {
  "campaigns": {
    "em_promo": {
      "name": "EveryMile 外幣簽帳優惠",
      "period_policy": {
        "mode": "composite",
        "windows": [
          {
            "endDate": "2026-06-30",
            "id": "window_2",
            "period": {
              "endDate": "2026-06-30",
              "startDate": "2026-04-01",
              "startDay": 1,
              "type": "promo"
            },
            "startDate": "2026-04-01"
          },
          {
            "endDate": "2026-03-31",
            "id": "window_1",
            "period": {
              "endDate": "2026-03-31",
              "startDate": "2026-01-01",
              "type": "promo"
            },
            "priority": 1,
            "startDate": "2026-01-01"
          }
        ]
      }
    },
    "winter_promo": {
      "name": "HSBC 最紅冬日賞",
      "period_policy": {
        "mode": "fixed",
        "windows": [
          {
            "endDate": "2026-02-28",
            "id": "window_1",
            "period": {
              "endDate": "2026-02-28",
              "startDate": "2025-12-01",
              "type": "promo"
            },
            "priority": 1,
            "startDate": "2025-12-01"
          }
        ]
      }
    }
  },
  "cards": {
    "hsbc_easy": {
      "name": "HSBC Easy Card / 白金卡"
    },
    "hsbc_gold_student": {
      "name": "HSBC 滙財金卡 (學生卡)"
    },
    "hsbc_unionpay_std": {
      "name": "HSBC 銀聯雙幣"
    }
  },
  "categories": {},
  "modules": {
    "easy_moneyback_bonus": {
      "desc": "Easy Card 易賞錢6倍 (2.4%)",
      "promo_end": "2026-12-31",
      "rate": 0.024,
      "valid_from": "2025-05-19",
      "valid_to": "2026-12-31"
    },
    "easy_moneyback_fortress_6x": {
      "desc": "易賞錢：豐澤 6倍 (1.2%)"
    },
    "easy_moneyback_pns_watsons_6x": {
      "desc": "易賞錢：百佳/屈臣氏 6倍 (2.4%)"
    },
    "em_designated": {
      "desc": "EveryMile 指定商戶 (2.5%)"
    },
    "em_grocery_low": {
      "desc": "EveryMile 超市 (0.4%)"
    },
    "em_overseas_bonus": {
      "desc": "EveryMile 外幣簽帳優惠 (1.5%)"
    },
    "pulse_china_bonus": {
      "cap_key": "pulse_china_bonus_cap",
      "cap_limit": 80000,
      "cap_mode": "spending",
      "desc": "中國內地/澳門流動支付 (2%)",
      "promo_end": "2026-06-30",
      "rate": 0.02,
      "valid_from": "2026-01-01",
      "valid_to": "2026-06-30"
    },
    "red_designated_bonus": {
      "cap_key": "red_designated_cap",
      "cap_limit": 100,
      "cap_mode": "reward",
      "desc": "Red Card 指定商戶 (7.6%)",
      "promo_end": "2026-03-31",
      "rate": 0.076,
      "valid_from": "2025-09-01",
      "valid_to": "2026-03-31"
    },
    "red_hot_variable": {
      "cap_key": "red_hot_variable_cap",
      "cap_limit": 2000,
      "cap_mode": "reward",
      "desc": "HSBC 最紅自主獎賞",
      "promo_end": "2026-12-31",
      "rate_per_x": 0.004,
      "valid_from": "2026-01-01",
      "valid_to": "2026-12-31"
    },
    "red_online": {
      "cap_key": "red_online_cap",
      "cap_limit": 400,
      "cap_mode": "reward",
      "desc": "Red Card 網上購物 (3.6%)",
      "promo_end": "2026-03-31",
      "rate": 0.04,
      "valid_from": "2025-09-01",
      "valid_to": "2026-03-31"
    },
    "sc_cathay_airlines": {
      "desc": "渣打國泰Mastercard 國泰/香港快運額外里數"
    },
    "sc_cathay_dining_hotel": {
      "desc": "食肆/酒店 $4/里"
    },
    "student_tuition_bonus": {
      "cap_key": "student_tuition_cap",
      "cap_limit": 200,
      "cap_mode": "reward",
      "desc": "學生卡學費回贈 (2.4%)",
      "promo_end": "2026-03-31",
      "rate": 0.024,
      "valid_from": "2025-10-01",
      "valid_to": "2026-03-31"
    },
    "vs_red_hot_bonus": {
      "cap_key": "vs_red_hot_bonus_cap",
      "cap_limit": 100000,
      "cap_mode": "spending",
      "desc": "Visa Signature 特別獎賞 (1.2%)",
      "multiplier": 3,
      "promo_end": "2026-12-31",
      "rate_per_x": 0.004,
      "valid_from": "2026-01-01",
      "valid_to": "2026-12-31"
    }
  },
  "trackers": {
    "em_overseas_mission": {
      "desc": "🌏 EveryMile 外幣簽帳優惠"
    },
    "winter_tracker": {
      "desc": "❄️ 最紅冬日賞"
    }
  },
  "version": 1
};
