// js/data_overrides.js
// Generated by tools/workbench.js apply
// Core overrides are higher risk: validate with golden cases before merge.
const CORE_OVERRIDES = {
  "campaignRegistry": {},
  "campaigns": {
    "ae_explorer_075x_toggle": {
      "promo_url": "https://www.americanexpress.com/zh-hk/benefits/offers/travel/explorer-overseas-spend-offer/?extlink=HO-Display-fx-spend-fx-spend-zh-a",
      "registration_url": "https://global.americanexpress.com/enrollments/oletenroll?campaignId=hkexp075xtravel1hk26&channel=IBW&locale=zh-HK",
      "tnc_url": "https://www.americanexpress.com/content/dam/amex/hk/ch/staticassets/pdf/cards/explorer-credit-card/MRTnC_CHI.pdf"
    },
    "ae_explorer_2026h1": {
      "promo_type": "custom",
      "promo_url": "https://www.americanexpress.com/zh-hk/benefits/offers/travel/explorer-overseas-spend-offer/?extlink=HO-Display-fx-spend-fx-spend-zh-a",
      "registration_url": "https://global.americanexpress.com/enrollments/oletenroll?campaignId=hkexp07xtravel1hk26&channel=IBW&locale=zh-HK",
      "tnc_url": "https://www.americanexpress.com/content/dam/amex/hk/ch/staticassets/pdf/cards/explorer-credit-card/MRTnC_CHI.pdf"
    },
    "ae_explorer_online_2026": {
      "promo_type": "custom",
      "promo_url": "https://www.americanexpress.com/zh-hk/benefits/offers/shopping/5x-offer/index.html",
      "registration_url": "https://global.americanexpress.com/enrollments/oletenroll?campaignId=hkexplorer5xoffer26&channel=IBW&locale=zh-HK",
      "tnc_url": "https://www.americanexpress.com/content/dam/amex/hk/ch/staticassets/pdf/cards/explorer-credit-card/MRTnC_CHI.pdf"
    },
    "ae_pcc_double_points_2026": {
      "promo_type": "custom",
      "promo_url": "https://www.americanexpress.com/hk/ch/benefits/shopping/offers/shopping/platinum-credit-card-double-points.html",
      "tnc_url": "https://www.americanexpress.com/content/dam/amex/hk/benefits/shopping/offers/pdf/Double_Point_Plat_G_2026_TnC.pdf"
    },
    "ae_pcc_program_3x_2026": {
      "promo_type": "custom",
      "promo_url": "https://www.americanexpress.com/hk/ch/benefits/shopping/offers/shopping/platinum-credit-card-double-points.html",
      "tnc_url": "https://www.americanexpress.com/content/dam/amex/hk/benefits/shopping/offers/pdf/Double_Point_Plat_G_2026_TnC.pdf"
    },
    "ae_platinum_9x_2026h1": {
      "promo_type": "custom",
      "promo_url": "https://www.americanexpress.com/zh-hk/benefits/offers/shopping/platinum-membership-rewards-accelerator/",
      "registration_url": "https://global.americanexpress.com/enrollments/oletenroll?campaignId=hkbonusplatmracc9x25&channel=IBW&locale=zh-HK",
      "tnc_url": "https://www.americanexpress.com/content/dam/amex/hk/benefits/pdf/TnCs_platinum-membership-rewards-accelerator.pdf"
    },
    "aeon_wakuwaku_2025_2026": {
      "promo_type": "custom"
    },
    "bea_unionpay_diamond_2025_2026h1": {
      "promo_type": "custom"
    },
    "boc_go_offer": {
      "promo_type": "custom"
    },
    "boc_go_offer_platinum": {
      "promo_type": "mission_multi_cap"
    },
    "boc_sogo_mobile_offer": {
      "promo_type": "custom"
    },
    "citi_rewards_bonus": {
      "promo_type": "custom"
    },
    "em_promo": {
      "name": "EveryMile 外幣簽賬優惠",
      "period_policy": {
        "mode": "composite",
        "windows": [
          {
            "endDate": "2026-06-30",
            "id": "window_2",
            "period": {
              "endDate": "2026-06-30",
              "startDate": "2026-04-01",
              "startDay": 1,
              "type": "promo"
            },
            "startDate": "2026-04-01"
          },
          {
            "endDate": "2026-03-31",
            "id": "window_1",
            "period": {
              "endDate": "2026-03-31",
              "startDate": "2026-01-01",
              "type": "promo"
            },
            "priority": 1,
            "startDate": "2026-01-01"
          }
        ]
      }
    },
    "fubon_infinite_overseas_2026": {
      "promo_type": "custom"
    },
    "fubon_travel_overseas_2026": {
      "promo_type": "custom"
    },
    "fubon_travel_upgrade_promo": {
      "promo_type": "custom"
    },
    "sim_promo": {
      "promo_type": "mission_multi_cap"
    },
    "sim_world_promo": {
      "promo_type": "mission_multi_cap"
    },
    "winter_promo": {
      "name": "HSBC 最紅冬日賞",
      "period_policy": {
        "mode": "fixed",
        "windows": [
          {
            "endDate": "2026-02-28",
            "id": "window_1",
            "period": {
              "endDate": "2026-02-28",
              "startDate": "2025-12-01",
              "type": "promo"
            },
            "priority": 1,
            "startDate": "2025-12-01"
          }
        ]
      }
    }
  },
  "cards": {
    "ae_explorer": {
      "promo_url": "https://www.americanexpress.com/zh-hk/campaigns/platinum-explorer-dualcards/?sourcecode=A0000HPA4F&cpid=100593908&intlink=hk-zh-hp-product1-all-Explorer-062023",
      "registration_url": "https://www.americanexpress.com/zh-hk/campaigns/platinum-explorer-dualcards/?sourcecode=A0000HPA4F&cpid=100593908&intlink=hk-zh-hp-product1-all-Explorer-062023",
      "source_url": "https://www.americanexpress.com/zh-hk/campaigns/platinum-explorer-dualcards/?sourcecode=A0000HPA4F&cpid=100593908&intlink=hk-zh-hp-product1-all-Explorer-062023",
      "tnc_url": "https://www.americanexpress.com/content/dam/amex/hk/ch/staticassets/pdf/cards/explorer-credit-card/MRTnC_CHI.pdf"
    },
    "ae_platinum": {
      "promo_url": "https://www.americanexpress.com/hk/ch/benefits/the-platinum-card/",
      "registration_url": "https://www.americanexpress.com/hk/ch/benefits/the-platinum-card/",
      "tnc_url": "https://www.americanexpress.com/content/dam/amex/hk/benefits/pdf/TnCs_platinum-membership-rewards-accelerator.pdf"
    },
    "ae_platinum_credit": {
      "promo_url": "https://www.americanexpress.com/zh-hk/benefits/offers/the-platinum-credit-card/",
      "registration_url": "https://www.americanexpress.com/hk/ch/credit-cards/platinum-credit-card/?linknav=hk-ch-amex-cardshop-allcards-learn-PlatinumCreditCard-fc",
      "tnc_url": "https://www.americanexpress.com/content/dam/amex/hk/benefits/shopping/offers/pdf/Double_Point_Plat_G_2026_TnC.pdf"
    },
    "hsbc_easy": {
      "name": "HSBC Easy Card / 白金卡"
    },
    "hsbc_gold_student": {
      "name": "HSBC 滙財金卡 (學生卡)"
    },
    "hsbc_unionpay_std": {
      "name": "HSBC 銀聯雙幣"
    },
    "sc_cathay_priority": {
      "name": "渣打國泰 Mastercard (優先理財)"
    },
    "sc_cathay_private": {
      "name": "渣打國泰 Mastercard (優先私人)"
    },
    "sc_cathay_std": {
      "name": "渣打國泰 Mastercard"
    },
    "sc_simply_cash": {
      "name": "渣打 Simply Cash Visa"
    },
    "sc_smart": {
      "name": "渣打 Smart Card"
    }
  },
  "categories": {},
  "modules": {
    "ae_explorer_fx_7x_bonus_2026h1": {
      "desc": "海外額外 +7X"
    },
    "ae_explorer_fx_travel_bonus_075_2026h1": {
      "desc": "海外/旅遊額外 +0.75X"
    },
    "ae_explorer_online_5x_bonus_2026": {
      "desc": "指定網上商戶額外 +2X"
    },
    "ae_explorer_travel_7x_bonus_2026h1": {
      "desc": "旅遊/機票額外 +7X"
    },
    "citi_cb_base": {
      "desc": "基本簽賬回贈"
    },
    "citi_cb_special": {
      "desc": "本地食肆、酒店及外幣"
    },
    "easy_moneyback_bonus": {
      "desc": "易賞錢指定商戶 6倍",
      "promo_end": "2026-12-31",
      "rate": 0.024,
      "valid_from": "2025-05-19",
      "valid_to": "2026-12-31"
    },
    "easy_moneyback_fortress_6x": {
      "desc": "易賞錢：豐澤 6倍"
    },
    "easy_moneyback_pns_watsons_6x": {
      "desc": "易賞錢：百佳/屈臣氏 6倍"
    },
    "em_designated": {
      "desc": "EveryMile 指定商戶"
    },
    "em_grocery_low": {
      "desc": "EveryMile 超市"
    },
    "em_overseas_bonus": {
      "desc": "EveryMile 外幣簽賬優惠"
    },
    "pulse_china_bonus": {
      "cap_key": "pulse_china_bonus_cap",
      "cap_limit": 80000,
      "cap_mode": "spending",
      "desc": "中國內地/澳門流動支付",
      "promo_end": "2026-06-30",
      "rate": 0.02,
      "valid_from": "2026-01-01",
      "valid_to": "2026-06-30"
    },
    "red_hot_variable": {
      "cap_key": "red_hot_variable_cap",
      "cap_limit": 2000,
      "cap_mode": "reward",
      "desc": "HSBC 最紅自主獎賞",
      "promo_end": "2026-12-31",
      "rate_per_x": 0.004,
      "valid_from": "2026-01-01",
      "valid_to": "2026-12-31"
    },
    "sc_cathay_airlines": {
      "desc": "渣打國泰Mastercard 國泰/香港快運額外里數"
    },
    "sc_cathay_dining_hotel": {
      "desc": "食肆/酒店 $4/里"
    },
    "sc_simply_cash_base": {
      "desc": "任何港幣消費"
    },
    "sc_simply_cash_foreign": {
      "desc": "任何外幣消費"
    },
    "student_tuition_bonus": {
      "cap_key": "student_tuition_cap",
      "cap_limit": 200,
      "cap_mode": "reward",
      "desc": "學生卡學費回贈",
      "promo_end": "2026-03-31",
      "rate": 0.024,
      "valid_from": "2025-10-01",
      "valid_to": "2026-03-31"
    },
    "vs_red_hot_bonus": {
      "cap_key": "vs_red_hot_bonus_cap",
      "cap_limit": 100000,
      "cap_mode": "spending",
      "desc": "Visa Signature 特別獎賞",
      "multiplier": 3,
      "promo_end": "2026-12-31",
      "rate_per_x": 0.004,
      "valid_from": "2026-01-01",
      "valid_to": "2026-12-31"
    }
  },
  "trackers": {
    "em_overseas_mission": {
      "desc": "🌏 EveryMile 外幣簽賬優惠"
    },
    "winter_tracker": {
      "desc": "❄️ 最紅冬日賞"
    }
  },
  "version": 2
};
